import type { ApprovalTask, NotificationItem, WorkflowTemplate } from "@/lib/types";

export const departments = [
  "Finance",
  "Human Resources",
  "Procurement",
  "Operations",
  "Legal",
  "Sales",
  "IT",
  "Administration",
];

export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: "finance-invoice",
    name: "Finance invoice approval",
    business: "Asia Allied Infrastructure",
    department: "Finance",
    documentTypes: ["Invoice PDF", "Invoice photo", "Excel schedule"],
    documents: [
      {
        id: "invoice-pdf",
        documentType: "Invoice",
        format: "pdf",
        required: true,
        fields: [
          {
            name: "invoice_vendor",
            label: "Vendor",
            type: "text",
            required: true,
            source: "ocr",
            instructions: "Extract the supplier or vendor legal name.",
            documentId: "invoice-pdf",
          },
          {
            name: "invoice_total",
            label: "Invoice total",
            type: "currency",
            required: true,
            source: "ocr",
            instructions: "Use the grand total including tax.",
            documentId: "invoice-pdf",
          },
        ],
      },
      {
        id: "excel-schedule",
        documentType: "Excel schedule",
        format: "excel_csv",
        required: false,
        fields: [
          {
            name: "line_items",
            label: "Line items",
            type: "table",
            required: false,
            source: "excel",
            instructions: "Keep item, quantity, unit price, and subtotal columns.",
            documentId: "excel-schedule",
          },
        ],
      },
    ],
    languages: ["English", "Traditional Chinese", "Simplified Chinese"],
    fields: [
      {
        name: "vendor",
        label: "Vendor",
        type: "text",
        required: true,
        source: "ai",
        instructions: "Extract the supplier or vendor legal name.",
      },
      {
        name: "invoice_total",
        label: "Invoice total",
        type: "currency",
        required: true,
        source: "ocr",
        instructions: "Use the grand total including tax.",
      },
      {
        name: "line_items",
        label: "Line items",
        type: "table",
        required: false,
        source: "excel",
        instructions: "Keep item, quantity, unit price, and subtotal columns.",
      },
    ],
    steps: [
      {
        name: "Department review",
        role: "Department reviewer",
        approverName: "Department reviewer",
        approverEmail: "department.reviewer@example.com",
        department: "Finance",
        dueInHours: 24,
        escalationRole: "Finance manager",
        escalationName: "Finance manager",
        escalationEmail: "finance.manager@example.com",
        condition: "Always",
      },
      {
        name: "Supervisor endorsement",
        role: "Supervisor",
        approverName: "Supervisor",
        approverEmail: "supervisor@example.com",
        department: "Requester department",
        dueInHours: 48,
        escalationRole: "Department head",
        escalationName: "Department head",
        escalationEmail: "department.head@example.com",
        condition: "Always",
      },
      {
        name: "CFO approval",
        role: "CFO delegate",
        approverName: "CFO delegate",
        approverEmail: "cfo.delegate@example.com",
        department: "Finance",
        dueInHours: 24,
        escalationRole: "CFO",
        escalationName: "CFO",
        escalationEmail: "cfo@example.com",
        condition: "invoice_total >= 10000",
      },
    ],
  },
];

export const approvalTasks: ApprovalTask[] = [
  {
    id: "APR-1048",
    title: "Cloud subscription invoice",
    workflow: "Finance invoice approval",
    requester: "Mandy Chan",
    requesterEmail: "mandy.chan@example.com",
    department: "IT",
    status: "pending",
    due: "Today, 17:00",
    value: "HKD 8,400",
    currentStep: "Department review",
    currentOwner: "derrick@example.com",
    participants: ["mandy.chan@example.com", "derrick@example.com"],
    lastAction: "Submitted by Mandy Chan",
    extractedFields: {
      Vendor: "Northstar Cloud Limited",
      "Invoice no.": "INV-2026-0612",
      Total: "HKD 8,400",
      Language: "English",
    },
    auditTrail: [
      {
        id: "APR-1048-event-1",
        action: "submitted",
        actor: "Mandy Chan",
        actorEmail: "mandy.chan@example.com",
        timestamp: "2026-06-17 09:10",
        detail: "Request submitted.",
      },
      {
        id: "APR-1048-event-2",
        action: "assigned",
        actor: "System",
        actorEmail: "system@example.com",
        timestamp: "2026-06-17 09:12",
        detail: "Assigned to Derrick Pang for department review.",
        targetEmail: "derrick@example.com",
      },
    ],
  },
  {
    id: "APR-1042",
    title: "Office renovation progress photos",
    workflow: "Operations site endorsement",
    requester: "Leo Wong",
    requesterEmail: "leo.wong@example.com",
    department: "Operations",
    status: "overdue",
    due: "Yesterday, 15:00",
    value: "Photo evidence",
    currentStep: "Supervisor endorsement",
    currentOwner: "derrick@example.com",
    participants: ["leo.wong@example.com", "derrick@example.com"],
    lastAction: "Escalated to supervisor endorsement",
    extractedFields: {
      Location: "Kwun Tong office",
      "Observed work": "Ceiling and cabling progress",
      Risk: "Moderate",
      Language: "Mixed Chinese and English",
    },
    auditTrail: [
      {
        id: "APR-1042-event-1",
        action: "submitted",
        actor: "Leo Wong",
        actorEmail: "leo.wong@example.com",
        timestamp: "2026-06-16 10:25",
        detail: "Progress photos submitted.",
      },
      {
        id: "APR-1042-event-2",
        action: "assigned",
        actor: "System",
        actorEmail: "system@example.com",
        timestamp: "2026-06-16 10:30",
        detail: "Assigned to Derrick Pang for supervisor endorsement.",
        targetEmail: "derrick@example.com",
      },
    ],
  },
  {
    id: "APR-1039",
    title: "Quarterly training expense sheet",
    workflow: "HR training reimbursement",
    requester: "Suki Lee",
    requesterEmail: "suki.lee@example.com",
    department: "Human Resources",
    status: "escalated",
    due: "Escalated 2h ago",
    value: "12 rows",
    currentStep: "Finance verification",
    currentOwner: "derrick@example.com",
    participants: ["suki.lee@example.com", "finance.manager@example.com", "derrick@example.com"],
    lastAction: "Escalated to Finance manager",
    extractedFields: {
      "Sheet count": "3",
      "Rows parsed": "12",
      Total: "HKD 21,980",
      Language: "Traditional Chinese",
    },
    auditTrail: [
      {
        id: "APR-1039-event-1",
        action: "submitted",
        actor: "Suki Lee",
        actorEmail: "suki.lee@example.com",
        timestamp: "2026-06-15 14:05",
        detail: "Training expense sheet submitted.",
      },
      {
        id: "APR-1039-event-2",
        action: "assigned",
        actor: "System",
        actorEmail: "system@example.com",
        timestamp: "2026-06-15 14:08",
        detail: "Assigned to Derrick Pang for finance verification.",
        targetEmail: "derrick@example.com",
      },
    ],
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "N-1",
    title: "Approval due soon",
    body: "APR-1048 is due today at 17:00.",
    time: "12 min ago",
    unread: true,
  },
  {
    id: "N-2",
    title: "Task escalated",
    body: "APR-1039 was escalated to Finance manager.",
    time: "2h ago",
    unread: true,
  },
  {
    id: "N-3",
    title: "Delegation active",
    body: "Your approval authority is delegated to Alex Ho this Friday.",
    time: "Yesterday",
    unread: false,
  },
];
